apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: tomcate-deployment
spec:
  selector:
    matchLabels:
      app: tomcat
  replicas: 1
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcate
        image: tomcat:9.0
        ports:
        - containerPort: 8080